import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        fetch: 'readonly',
      },
    },
    rules: {
      quotes: 'off',
      semi: 'off',
      indent: 'off',
      'comma-dangle': 'off',
      'max-len': 'off',

      'no-unused-vars': 'off',
      'no-use-before-define': 'off',
      'require-await': 'off',
      'no-await-in-loop': 'off',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-extend-native': 'error',
      'no-caller': 'error',
      'no-proto': 'error',
      'array-callback-return': 'error',
      'no-console': 'warn',
      'no-alert': 'warn',
      eqeqeq: ['warn', 'always'],
      'no-throw-literal': 'warn',
      'no-promise-executor-return': 'warn',
      'no-async-promise-executor': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'no-empty': 'warn',
      'no-empty-function': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-return': 'warn',
      'guard-for-in': 'warn',
      'no-param-reassign': 'warn',
    },
  },
];
